import { 
    Zap, 
    BatteryFull, 
    BatteryCharging, 
    Target, 
    Activity, 
    Layers, 
    Fuel, 
    Clock, 
    Coins, 
    Car, 
    Milestone, 
    TrendingUp,
    Sun,
    SunDim,
} from 'lucide-react';

export const Icons = {
    BoltIcon: Zap,
    BatteryFullIcon: BatteryFull,
    BatteryChargingIcon: BatteryCharging,
    BatteryTargetIcon: Target,
    EfficiencyIcon: Activity,
    PhaseIcon: Layers,
    EvStationIcon: Fuel,
    PowerIcon: Zap,
    EnergyIcon: BatteryFull,
    ClockIcon: Clock,
    CurrencyForintIcon: Coins,
    CarIcon: Car,
    FuelIcon: Fuel,
    DistanceIcon: Milestone,
    SavingsIcon: TrendingUp,
    SunIcon: Sun,
    SunDimIcon: SunDim,
};
